### PR TITLE
Fix the project to make it runnable

### LINKED ISSUE #1: Fix the project to make it runnable
There are some problems with a project that I encountered while I was trying to run it:

- Dependencies should be explicitly defined in `package.json`. Use:
  ```bash
  npm install --save <lib>
  ```
- Formatting is absent, but `.eslintrc` exists. To not forget to use prettier, you can set it to automatically format your file each time you save it. Personally, I use it in VSCode and it helps me a lot and not only with js.
- Bugs in implementation. I encountered:
    - `shortc.js`: `chalk` is included but not used
    - `commands.js`: `chalk` is used but not included :)
    - `commands.js`: function `addCommand` uses `pathFile` that is not defined.

Fix these problems, make the Pull Request and I will be glad to review it!

### PR DESCRIPTION
**Pull request by ShpylovyiRoman**
add dependencies for packages, use linter, fix some bugs
issue fixes #1

### CODE REVIEW

**Comment by G1gg1L3s** [comment]
There is one issue. You included `input.json` into git, which is not desirable, because this file varies from user to user. And, if you delete this file, this what you get:
```bash
$ node shortc.js add --com "my" --desc "my"
my my
/home/gdobn/Code/romka/shortc/commands.js:12
    if (err) throw err;             ^

[Error: ENOENT: no such file or directory, open 'input.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'input.json'
}
```
If the file doesn't exist, we should create it empty, and throw errors if if fails.

File: commands.js [hunk 1]
```diff
@@ -1,13 +1,28 @@
 'use strict';
 const fs = require('fs');
 const chalk = require('chalk');
+const pathFile = 'input.json';
+
+function ifExist(path) {
```
Comment (G1gg1L3s) [inline commands.js]: I would name it something like `createIfNotExists` or `ensureExists`. From `ifExists` it is not fully clear what it does.

File: commands.js [hunk 2]
```diff
@@ -1,13 +1,28 @@
...
+    } else {
+      fs.writeFileSync(path, '[]');
+    }
+  } catch (error) {
+    console.log(error);
+  }
+}
 
 function readFile(path) {
+  ifExist(path);
```
Comment (G1gg1L3s) [inline commands.js]: There are repetitions, which we will eliminate in the future. For now, it's ok :)

**Comment by G1gg1L3s** [comment]
Did you include all dependencies? Because I still get the same errors:
```
$ node shortc.js add --com='git add' --desc='This command can help'
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module 'yargs'
Require stack:
- /home/gdobn/Code/romka/shortc/shortc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/gdobn/Code/romka/shortc/shortc.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/gdobn/Code/romka/shortc/shortc.js' ]
}
```

**Comment by G1gg1L3s** [comment]
Ok, I think this PR should be merged!

**Review by G1gg1L3s — APPROVED** [review]
One more thing: please use more descriptive name for commits. For example, instead of

> file dependencies fix

You could write something like

> Add yargs to the dependencies in package.json

If you are interested, here you can find a great tutorial about how to write git messages:
https://chris.beams.io/posts/git-commit/
